source "https://rubygems.org"

ruby ">= 3.3.0"

# Rails フレームワーク
gem "rails", "~> 7.1.3"

# PostgreSQL アダプター (本番用)
# gem "pg", "~> 1.5"

# SQLite アダプター (開発用)
gem "sqlite3", "~> 2.6"

# Puma ウェブサーバー
gem "puma", ">= 5.0"

# JSON シリアライザー
gem "jsonapi-serializer", "~> 2.2"

# 認証
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.8"

# 認可
gem "pundit", "~> 2.3"

# CORS
gem "rack-cors", "~> 2.0"

# ページネーション
gem "kaminari", "~> 1.2"

# 環境変数
gem "dotenv-rails", "~> 3.0"

# タイムゾーン
gem "tzinfo-data", platforms: %i[ windows jruby ]

# パフォーマンス
gem "bootsnap", require: false

# 画像処理
gem "image_processing", "~> 1.12"

# AWS S3
gem "aws-sdk-s3", "~> 1.143"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
end

group :development do
  gem "rubocop", "~> 1.60", require: false
  gem "rubocop-rails", "~> 2.23", require: false
  gem "rubocop-rspec", "~> 2.26", require: false
end

group :test do
  gem "shoulda-matchers", "~> 6.1"
  gem "database_cleaner-active_record", "~> 2.1"
end
